# Generated by Django 5.0.6 on 2024-06-20 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preorder', '0004_remove_profile_preferedsellingpoint'),
        ('sellingPoint', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedbread',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='owner',
        ),
        migrations.AlterField(
            model_name='preorder',
            name='sellingPoint',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='sellingPoint.sellingpoint'),
        ),
        migrations.DeleteModel(
            name='bread',
        ),
        migrations.DeleteModel(
            name='orderedBread',
        ),
        migrations.DeleteModel(
            name='profile',
        ),
        migrations.DeleteModel(
            name='sellingPoint',
        ),
    ]
