# Generated by Django 5.0.6 on 2024-06-20 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='bread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='../default_profile_qdjgyp', upload_to='images/')),
                ('description', models.CharField(max_length=255)),
                ('canBeSliced', models.BooleanField(default=False)),
                ('canBeInQuarters', models.BooleanField(default=False)),
                ('price', models.IntegerField()),
                ('pricePerKilogram', models.IntegerField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
