# Generated by Django 5.0.6 on 2024-06-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bread', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bread',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
