# Generated by Django 5.0.6 on 2024-06-23 09:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bread', '0003_alter_bread_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bread',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
