# Generated by Django 5.0.6 on 2024-06-21 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bread', '0002_alter_bread_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bread',
            options={'ordering': ['name']},
        ),
    ]
