# Generated by Django 5.0.6 on 2024-06-23 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactUs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'ordering': ['-createdAt']},
        ),
    ]
