# Generated by Django 5.0.6 on 2024-06-17 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preorder', '0003_alter_profile_preferedsellingpoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='preferedSellingPoint',
        ),
    ]
