# Generated by Django 5.0.6 on 2024-06-21 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellingPoint', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sellingpoint',
            options={'ordering': ['name']},
        ),
    ]
